# Generated by Django 5.0.4 on 2024-05-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
            ],
        ),
    ]
